### ISSUE TITLE
Can't connect to Google sites while using iframe

### ISSUE THREAD

**Issue by ollesjostrom** [IrisBroadcast/OphrysSignage#6] opened 2020-02-19 07:20 UTC
I can't display a Google site while using an iframe code. Guessing that it's because I connect through http:// to the Orphys, and Google expects a https connection. 

This works: 

![asdasd](https://user-images.githubusercontent.com/61224252/74810852-9134b280-52f0-11ea-9cde-eb46da7b06cd.PNG)

This doesn't:

![fghfgh](https://user-images.githubusercontent.com/61224252/74810888-a4e01900-52f0-11ea-9bff-d2cc6075ce33.PNG)

**Comment by ollesjostrom** [comment] 2020-02-19 07:22
And it's all the same even if I use just one url1= after the view/-code.

**Comment by cbjornram** [comment] 2020-02-19 08:37
What happens when you try it?

I'm quite sure that the links you have in your example aren't possible to embed in an iframe (which is what all the different /view:s does). Google provides iframe-friendly calendar links if you go to the settings of your calendar (provided that the calendar is open for everyone). However I'm afraid those will not work the way you wish either because those calendar links use variables and Ophrys can't yet distinguish between its own variables and the external urls' variables.

What I suppose you could do is to create a "/view/info"-site (a new function that should be available in the next few days). This lets you create your own html-site right within Ophrys, and in that site you should be able to use Google Calendar's embed-functions (also available in your Calendar settings). I have not tried this myself yet but I'm preparing an Ophrys right now to test it. I will write again when I know more.

**Comment by cbjornram** [comment] 2020-02-19 08:54
I can confirm that what you want is possible with /view/info. The way it works is that in the Ophrys "URL to display"-field you write `http://localhost:82/view/info`. Then you can go to a new settings-view which presents you to a text field where you can enter your own html-code to "build" you own custom view. To display two google calendars side by side on an 1920*1080-monitor I wrote:

```html
<iframe src="https://calendar.google.com/calendar/embed?src=6tpsgprcqm0er887jut3bkl3u0%40group.calendar.google.com&ctz=Europe%2FStockholm" style="border: 0" width="930" height="1080" frameborder="0" scrolling="no"></iframe>
<iframe src="https://calendar.google.com/calendar/embed?src=6tpsgprcqm0er887jut3bkl3u0%40group.calendar.google.com&ctz=Europe%2FStockholm" style="border: 0" width="930" height="1080" frameborder="0" scrolling="no"></iframe>
```

This update should be rolled out soon to all Ophrys at our workplace. If you wish to get it immediately you can download an updated custom image from the same place as usual.

**Comment by cbjornram** [comment] 2020-02-20 12:08
With the most resent release of Ophrys another alternative solution is available. Instead of using /view/info you can use a /view/multi?viewid={ViewID}, and paste your desired URL:s in the URL 1 and URL 2 fields that you can find in view options. This does not directly solve your request (since only google can do that by allowing being embeded in iframes), but it might be an easier solution than to write the iframes yourself so I thought I'd mention it.

**Comment by djhenley** [comment] 2020-02-26 20:55
Closing the issue, please reopen if it doesn't work as intended.

**Closed by djhenley** 2020-02-26 20:55 UTC
